title: Fan Yang
description: Biomechanics • Active matter • Spatial omics
url: "https://fy26.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
academicons: true

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: single

author:
  name: Fan Yang
  avatar: /assets/img/avatar.png
  bio: "Biomechanics + active matter → programmable engineering and medical platforms."
  links:
    - label: Email
      icon: fas fa-envelope
      url: mailto:fy2@caltech.edu
    - label: Google Scholar
      icon: ai ai-google-scholar
      url: https://scholar.google.com/citations?user=DGkWTvIAAAAJ&hl=en
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/fy26

# Optional: enable academicons for Google Scholar icon
#(Place this in your _config.yml if you want the Scholar logo)
minimal_mistakes_skin: default
analytics: null
theme settings:
  author_profile: true
  footer:
    links:
      - label: Google Scholar
        icon: ai ai-google-scholar
        url: https://scholar.google.com/citations?user=DGkWTvIAAAAJ&hl=en